apiVersion: v1
kind: Service
metadata:
  name: {{ template "tempo.fullname" . }}-distributor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.distributorLabels" . | nindent 4 }}
  {{- with .Values.distributor.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.distributor.service.type }}
  ports:
    - name: http
      port: 3100
      targetPort: http
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
    {{- if .Values.traces.jaeger.thriftCompact }}
    - name: distributor-jaeger-thrift-compact
      port: 6831
      protocol: UDP
      targetPort: jaeger-compact
    {{- end }}
    {{- if .Values.traces.jaeger.thriftBinary }}
    - name: distributor-jaeger-thrift-binary
      port: 6832
      protocol: UDP
      targetPort: jaeger-binary
    {{- end }}
    {{- if .Values.traces.jaeger.thriftHttp }}
    - name: distributor-jaeger-thrift-http
      port: 14268
      protocol: TCP
      targetPort: jaeger-http
    {{- end }}
    {{- if .Values.traces.jaeger.grpc }}
    - name: distributor-jaeger-grpc
      port: 14250
      protocol: TCP
      targetPort: jaeger-grpc
    {{- end }}
    {{- if .Values.traces.zipkin }}
    - name: distributor-zipkin
      port: 9411
      protocol: TCP
      targetPort: zipkin
    {{- end }}
    {{- if or (.Values.traces.otlp.http) (.Values.traces.otlp.grpc) }}
    - name: distributor-otlp
      port: 55680
      protocol: TCP
      targetPort: otlp
    {{- end }}
    {{- if .Values.traces.opencensus }}
    - name: distributor-opencensus
      port: 55678
      protocol: TCP
      targetPort: opencensus
    {{- end }}
  {{- if .Values.distributor.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.distributor.service.loadBalancerIP  }}
  {{- end }}
  {{- with .Values.distributor.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "tempo.distributorSelectorLabels" . | nindent 4 }}

